In [1]:
import numpy as np
from math import pi

In [2]:
# 1

# 1. Создайте массив длины 10, заполненный нулями
# 2. Сделайте полученный массив неизменяемым
array = np.zeros(10)
array.flags.writeable = False
array.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [3]:
# 2

# 1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
# 2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
# 3. Составьте из полученных массивов координатную сеть (meshgrid)

array1 = np.linspace(0, 2*pi, num=5)
array2 = np.logspace(10, 100, num=5)

np.meshgrid(array1, array2)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

In [4]:
# 3
# Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [5]:
# 4

# 1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
# 2. Создайте массив из построенного генератора

def gen():
    for i in range(10):
        yield i 
        
np.fromiter(gen(), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 5

# Что будет выведено на экран?
# a = np.arange(4).reshape(2,2)
# a += 0.5
# print(a)

# Error (type a is int)

In [7]:
# 6

# Что будет выведено на экран?
# a = np.array([1])
# if a:
  #  print("True")
# else:
 #   print("False")

# a = np.array([1, 2, 3])
# if a:
  #  print("True")
# else:
  #  print("False")
    
# True
# Error (ambigious)

In [8]:
# 7


# Что будет выведено на экран?
# print(0 * np.nan)
# print(np.nan - np.nan)
# print(np.nan == np.nan)
# print(np.nan is np.nan)
# print(-np.inf < np.nan < np.inf)

'''
1. nan
2. nan
3. False
4. True
5. False 
''';

In [9]:
# 8

# Что будет выведено на экран?
# print(np.isnan(np.array([np.nan]).astype(np.int)))

# array([False])

In [10]:
# 9

# 1. Создайте масив из четырех элементов: 0, 10, 20, 30
# 2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  
# больше предыдущего элемента этой же строки на 1.

array = np.array([0, 10, 20, 30]).reshape(4, 1)
array + np.arange(5)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [11]:
# 10

# Какой shape будет у результата операции np.arange(5).reshape(1,-1) + np.arange(5).reshape(-1,1)?

# shape(1, 5) + shape(5, 1) = shape(5, 5)

In [12]:
# 11

# Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

x = np.ones((8, 8))
x[::2, ::2] = 0
x[1::2, 1::2] = 0
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [13]:
# 12

# 1. Создайте одномерный массив целых чисел от 1 до 5
# 2. Вставьте 0 между каждой парой соседних элементов

array = np.arange(1, 6)
size = array.shape[0]
np.insert(array, np.repeat(np.arange(1, size), 1), 0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

In [14]:
# 13

# Что будет выведено на экран?
# x = np.arange(36).reshape(2,3,2,3)
# print(x[...,0,...])

# error, because we can't have two ellipsis in this case

In [15]:
# 14

# Что будет выведено на экран?
# x = np.arange(16).reshape(4,4)
# y = x[:,[2,3]]
# y[:] = 0
# print(x)
# y = x[:,:2]
# y[:] = 0
# print(x)

x = np.arange(16).reshape(4,4)
y = x[:, [2,3]]
y[:] = 0
print(x)
y = x[:, :2]
y[:] = 0
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]]


In [16]:
# 15

# Замените отрицательные элементы массива нулем.

array = np.array([-2, -4, 5])
array[array < 0] = 0
array

array([0, 0, 5])

In [17]:
# 16

# На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) 
# составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)
x[np.any(x != x[:, 0].reshape(4, 1), axis=1)]

array([[1, 2, 3],
       [2, 2, 1]])

In [18]:
# 17

# Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей
# (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

# np.random.seed(21)
np.random.seed(42)
x = np.random.randint(10, size=10)
print(x)

a = np.zeros_like(x, dtype=bool)
a[:-1] = x[:-1] <= x[1:]
a[1:] = x[:-1] >= x[1:]
x[a]

[6 3 7 4 6 9 2 6 7 4]


array([3, 4, 2, 4])

In [19]:
# 18

# 1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
# 2. Отсортируйте строки массива по возрастанию значения во втором столбце

np.random.seed(3)
x = np.random.randint(9, size=9).reshape(3, 3)
print(x)
x[np.argsort(x[:, 1])]

[[8 3 8]
 [8 0 5]
 [3 5 7]]


array([[8, 0, 5],
       [8, 3, 8],
       [3, 5, 7]])

In [20]:
# 19

# Поменяйте местами первую и вторую строки двумерного массива

array = np.array([[1, 2, 3],
                  [4, 5, 6]])
array[[0, 1]] = array[[1, 0]]
array

array([[4, 5, 6],
       [1, 2, 3]])

In [21]:
# 20

# 1. Создайте массив 3x5, заполненный числами от 0 до 14
# 2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

array = np.arange(15).reshape(3, 5)
array[[0, 2], :][:, [1, 3]]

array([[ 1,  3],
       [11, 13]])

In [22]:
# 21

# Что будет выведено на экран?
# x = np.arange(5)
# x[[0,0,1]] = range(3)
# print(x)
# x[[1,2,1]] += 1
# print(x)

x = np.arange(5)
print(x)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[0 1 2 3 4]
[1 2 2 3 4]
[1 3 3 3 4]


In [23]:
# 22

# Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. 
# Какой из способов работает быстрее и почему?

# reshape (view or copy), ravel (view), flatten (copy), list(a.flat)

In [24]:
# 23

# 1. Создайте массив, заполненный случайными значениями
# 2. Замените максимальные значения массива средним

np.random.seed(0)
x = np.random.rand(10)
print(x)
x.max(), x.mean()
x[x==x.max()] = x.mean()
x

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.61576628, 0.38344152])

In [25]:
# 24 

# 1. Создайте двумерный массив 6x6, заполненный случайными значениями
# 2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

np.random.seed(2)
x = np.random.random((6, 6))
summa = np.sum(x, axis=1)
min_elements = np.amin(x, axis=0)
summa / min_elements

array([17.2822359 , 97.99640353, 16.08190941, 30.96187825,  7.38515487,
       27.81633868])

In [26]:
# 25

# 1. Создайте одномерный массив длины 10, заполненный случайными значениями
# 2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

x = np.random.randint(10, size=10)
print(x)
(x - np.min(x)) / (np.max(x) - np.min(x))

[8 5 9 9 9 3 0 0 2 8]


array([0.88888889, 0.55555556, 1.        , 1.        , 1.        ,
       0.33333333, 0.        , 0.        , 0.22222222, 0.88888889])

In [27]:
# 26

# Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу\

np.random.seed(100)
x = np.random.randint(20, size=25).reshape(5, 5)
x = x.astype(float)
mean_values = np.mean(x, axis=1)
x[x < 10] = np.nan
print(x)
means = np.nanmean(x, axis=0)
inds = np.where(np.isnan(x))
x[inds] = np.take(means, inds[1])
print(x)

[[nan nan nan 15. 16.]
 [10. nan nan nan 14.]
 [nan 17. 16. 15. nan]
 [11. 16. nan nan 12.]
 [nan nan 13. 19. nan]]
[[10.5        16.5        14.5        15.         16.        ]
 [10.         16.5        14.5        16.33333333 14.        ]
 [10.5        17.         16.         15.         14.        ]
 [11.         16.         14.5        16.33333333 12.        ]
 [10.5        16.5        13.         19.         14.        ]]


In [28]:
# 27

# Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

np.random.seed(3)
x = np.random.randint(2, size=25).reshape(5, 5)
x[-2][0] = 0
print(x)
np.all(x[:, :] == 0, axis=0)

[[0 0 1 1 0]
 [0 0 1 1 1]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 1 0 0]]


array([ True, False, False, False, False])

In [29]:
# 28

# 1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
# 2. Вычислите суммы элементов по двум последним осям

np.random.seed(3)
x = np.random.randint(10, size=144).reshape(3, 4, 3, 4)
np.sum(x, axis=(2, 3))

array([[74, 45, 52, 61],
       [27, 30, 48, 43],
       [41, 48, 69, 54]])

In [30]:
# 29

# 1. Любым способом создайте два массива одинаковой длины
# 2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива,
# а на нечетных - с соответствующих позиций второго

np.random.seed(3)
x = np.random.randint(10, size=10)
y = np.random.randint(20, size=10)
z = np.zeros(10)
z[::2] = x[::2]
z[1::2] = y[1::2]
print(x)
print(y)
z

[8 9 3 8 8 0 5 3 9 9]
[10  6  0 12  7 14 17  2  2  1]


array([ 8.,  6.,  3., 12.,  8., 14.,  5.,  2.,  9.,  1.])

In [31]:
# 30

# На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]) вычислите долю пропущенных значений

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
print(x)
np.isnan(x).sum()/np.prod(x.shape)

[[ 1.  2.]
 [nan  3.]
 [ 5.  5.]
 [nan nan]]


0.375

In [32]:
# 31

# На примере массива x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
# составьте массив из уникальных значений массива без учета nan

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
np.unique(x[~np.isnan(x)])

array([1., 2., 3., 5.])

In [33]:
# 32 

# На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов,
# перед которыми стоит нулевой

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[1:][x[1:] == np.diff(x)])

5

In [34]:
# 33

# Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. 
# В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

np.random.seed(3)
x = np.random.randint(10, size=10).astype(float)
y = np.random.randint(20, size=10).astype(float)
np.divide(x, y, out=np.zeros_like(x), where=y!=0)

array([0.8       , 1.5       , 0.        , 0.66666667, 1.14285714,
       0.        , 0.29411765, 1.5       , 4.5       , 9.        ])

In [35]:
# 34 

# Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). 
# Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i.
# В случае, если некоторый индекс встретился в массиве i несколько раз, 
# прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.\

x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

x + np.bincount(i, minlength=len(x))

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [36]:
# 35

# По заданному массиву y = np.bincount([0, 0, 3, 8, 10, 10, 11]) постройте массив x такой, чтобы np.bincount(x) = y

y = np.bincount([0, 0, 3, 8, 10, 10, 11]) 
x = np.repeat(np.arange(y.size), y)
x

array([ 0,  0,  3,  8, 10, 10, 11])

In [37]:
# 36

#  Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
# Решите задачу на примере массива x = np.array([0,1,2,0,6,6,7,4,5,4]).

x = np.array([0, 1, 2, 0, 6, 6, 7, 4, 5, 4])
unique, count = np.unique(x, return_counts=True)
unique[count == count.max()]

array([0, 4, 6])

In [38]:
# 37

# Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
# Решите задачу на примере массива x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]]), 
# в результате должен получиться список [array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])].

x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])
np.array_split(x, len(np.unique(x[:, :][:, 0])))

[array([[1, 2],
        [1, 3]]),
 array([[2, 2],
        [3, 4]]),
 array([[3, 5]])]

In [39]:
# 38

# По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, 
# сожержащих элементы из полуинтервалов [i * 10, (i+1) * 10), i = 0, 1, 2, …
# Решите задачу на примере массива x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20]),
# в результате должен получиться список [array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])].

x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])
groups = max(x) // 10 + 1
# np.array_split(np.sort(x), groups)

In [40]:
# 39

# Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. 
# Какой из способов работает быстрее?

# np.concatenate (use twice memory), np.vstack, np.append

In [41]:
# 40

# Для двух одномерных массивов x = np.arange(3) и y = np.arange(5) постройте 
# двумерный массив строки которого - всевозможные пары элементов из x и y.

x = np.arange(3)
y = np.arange(5)

np.array(np.meshgrid(x, y)).T.reshape(-1,2)

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4]])

In [42]:
# 41

# По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
# Решите задачу на примере массивов x = np.array([1,2,3,4]) и y = np.array([5,6,7,8]).

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.array(list(zip(x, y)))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [43]:
# 42

# По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив 
# в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых 
# вставлен массив полностью заполненный нулями.
# Решите задачу для списка l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])].

l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

In [44]:
# 43

# Преобразуйте одномерный массив x = np.array([3,7,2,5,0,9,8,2,4,5]) в двумерный массив, 
# первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

array = np.array([3, 7, 2, 5, 0, 9, 8, 2, 4, 5])
l = len(array) - (4 - 1)

def func(x, y):
    return array[x + y]

np.fromfunction(func, (l, 4), dtype=int)

array([[3, 7, 2, 5],
       [7, 2, 5, 0],
       [2, 5, 0, 9],
       [5, 0, 9, 8],
       [0, 9, 8, 2],
       [9, 8, 2, 4],
       [8, 2, 4, 5]])